server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finder?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Europe/Moscow
    username: raichu
    password: raichuxapassword228!
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.web: debug
